force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/invoicescontrollertest.cls
@isTest
private class invoicescontrollertest {

    @isTest
    static void testSave() {
        //Gather ingredients
        //need an invoice
        //need a linked opportunity
        //need a linked account
        Account testAccount = new Account(Name='Test');
        insert a;
        List<Opportunity> testOpp = new List<Opportunity>();
        Opportunity o = new Opportunity();
            o.AccountId = a.Id;
            o.Name = 'Test';
            o.Type = 'New Customer';
            o.Amount = 120000;
            o.StageName = 'Closed Lost';
            o.CloseDate = Date.today();
        insert o;
        testOpp.add(o);
        //need an instance of the class
        ApexPages.StandardSetController testSSC 
                      = new ApexPages.StandardSetController(new List<Opportunity>{ testOpp });
        
         Invoice__c testInvoice = new Invoice__c();
            testInvoice.Opportunity__c = o.Id;
            testInvoice.Account__c = o.AccountId;
            testInvoice.Amount__c = o.Amount;
            testInvoice.Due_Date__c = o.CloseDate + 90;
        
        InvoicesController invExt = new InvoicesController(testSSC);
        invExt.newinvoices.add(testInvoice);

        TEst.startTest();
        //Do something that needs testing
        PageReference testPR = invExt.save();
        test.stopTest();

        //Checks to see everything worked
        
    }
}