force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/BIlling_Contact__c.field-meta.xml
<CustomField>
    <fullName>BIlling_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BIlling Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Date__c</fullName>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/isFee__c.field-meta.xml
<CustomField>
    <fullName>isFee__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isFee</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/latefeeApplied__c.field-meta.xml
<CustomField>
    <fullName>latefeeApplied__c</fullName>
    <defaultValue>false</defaultValue>
    <label>latefeeApplied</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ShowScheduleController.cls
public with sharing class ShowScheduleController {
    private ApexPages.StandardController stdController;

    public ShowScheduleController(ApexPages.StandardController controller) {
        this.stdController = controller;
        aid = stdController.getId();
        loadAccount();
    }

    private Id aid;
    public Account acc {get;set;}

    public List<Invoice__c> newinvoices{get; set;}

    private void loadAccount(){
        acc = [SELECT Id, Name, (SELECT ID,Opportunity__c,Amount__c,Due_Date__c,isFee__c,latefeeApplied__c,Paid__c,Invoice_Date__c,Billing_Contact__c FROM Invoices__r WHERE Due_Date__c >= TODAY )
        FROM Account
        WHERE Id = :aid LIMIT 1];

        newInvoices = new List<Invoice__c>(acc.Invoices__r);
        

    }


}