force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Date__c</fullName>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/PresentInvoice__c.field-meta.xml
<CustomField>
    <fullName>PresentInvoice__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PresentInvoice</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/invoiceDelivery.cls
global class invoiceDelivery implements Database.Batchable<sObject> {


    global Database.QueryLocator start (Database.BatchableContext bc){
        Date cutoffDate = Date.today();
        
        String query = 'SELECT ID FROM Invoice__c ' +
        'WHERE Invoice_Date__c > :cutoffDate AND PresentInvoice__c = false';
        
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext bc, List<Invoice__c> invs){
        for (Invoice__c i : invs){
            i.PresentInvoice__c = true;
        }
        Database.update(invs,false);
    }

    //Do stuff on completion as needed
    global void finish(Database.BatchableContext bc){
        system.debug('Batch process: '+bc.getJobId() + ' completed');
    }

}