force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Date_Paid__c.field-meta.xml
<CustomField>
    <fullName>Date_Paid__c</fullName>
    <label>Date Paid</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Date__c</fullName>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/statementLineItemsController.cls
global class statementLineItemsController {
    public statementLineItemsController() {
        String query = 'SELECT ID, Name, (SELECT ID,Opportunity__r.Name, Amount__c, Date_Paid__c, Due_Date__c FROM Invoices__r WHERE Invoice_Date__c = LAST_N_MONTHS:1  OR Date_Paid__c = LAST_N_MONTHS:1) FROM Account' +
        'WHERE Id = "accountId ';
        relatedInvoices = Database.query(query);
    }
    global String accountId { get; set; }
    global List<Invoice__c> relatedInvoices { get; set; }



}